import { chromium } from '@playwright/test'
const OUT = '/private/tmp/claude-503/-Users-s-riva-Progetti-quaderno/32ddd232-26e3-4330-803d-3cdd663d8a13/scratchpad/shots'
const base = process.argv[2] ?? 'http://localhost:55603'
const browser = await chromium.launch({ channel: 'chromium' })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') errors.push(`[${m.type()}] ${m.text()}`) })
page.on('pageerror', e => errors.push(`[pageerror] ${e.message}`))
const shot = (n) => page.screenshot({ path: `${OUT}/${n}.png` })
const label = () => page.locator('header p').textContent().catch(() => '?')

await page.goto(base + '/#/')
await page.waitForTimeout(1500)
await shot('01-shelf-empty')
await page.getByRole('button', { name: 'Crea il tuo primo quaderno' }).click()
await page.waitForTimeout(600)
await shot('02-atelier')
await page.getByPlaceholder('Appunti di…').fill('Storia')
await page.getByRole('button', { name: 'Metti sulla mensola' }).click()
await page.waitForTimeout(2200)
await shot('03-reader-open')
console.log('label after open:', await label())

const editor = page.getByRole('textbox', { name: 'Testo della pagina 1' })
await editor.click()
await page.keyboard.insertText('Prima pagina di prova. ')
await page.waitForTimeout(400)

// flip forward, no reduced motion
const next = page.getByRole('button', { name: 'Pagina successiva' })
const prev = page.getByRole('button', { name: 'Pagina precedente' })
await next.click()
await page.waitForTimeout(300)
await shot('04-mid-flip')
await page.waitForTimeout(1200)
await shot('05-after-flip')
console.log('label after flip 1:', await label())
await next.click()
await page.waitForTimeout(1500)
console.log('label after flip 2:', await label())
await shot('06-after-flip2')
await prev.click()
await page.waitForTimeout(1500)
console.log('label after back:', await label())
await shot('07-after-back')
// leaf stuck? count motion divs
const stuck = await page.evaluate(() => document.querySelectorAll('[style*="preserve-3d"]').length)
console.log('flip leaves in DOM:', stuck)

// back to shelf
await page.getByRole('button', { name: 'Torna alla mensola' }).click()
await page.waitForTimeout(2000)
await shot('08-shelf-one')
// mobile
const m = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 })
m.on('pageerror', e => errors.push(`[m pageerror] ${e.message}`))
await m.goto(base + '/#/')
await m.waitForTimeout(1500)
await m.screenshot({ path: `${OUT}/09-mobile-shelf.png` })
await m.locator('canvas').first().click({ position: { x: 195, y: 400 } }).catch(() => {})
await m.waitForTimeout(2500)
await m.screenshot({ path: `${OUT}/10-mobile-after-click.png` })
console.log('mobile url:', m.url())
console.log('ERRORS:\n' + errors.join('\n'))
await browser.close()
