import { chromium } from '@playwright/test'
const browser = await chromium.launch({ channel: 'chromium' })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('https://quaderno-simiriva95s-projects.vercel.app/#/')
await page.getByRole('button', { name: 'Crea il tuo primo quaderno' }).click()
await page.getByPlaceholder('Appunti di…').fill('Prod')
await page.getByRole('button', { name: 'Metti sulla mensola' }).click()
await page.waitForURL(/#\/q\//); await page.waitForTimeout(1800)
await page.getByRole('textbox', { name: 'Testo della pagina 1' }).click()
await page.keyboard.insertText('test produzione ')
const next = page.getByRole('button', { name: 'Pagina successiva', exact: true })
await next.click(); await page.waitForTimeout(1000)
await next.click(); await page.waitForTimeout(1000)
console.log('label:', await page.locator('header p').textContent())
console.log('corners:', await page.getByRole('button', { name: /Gira alla pagina/ }).count())
console.log('leaves left:', await page.locator('[style*="preserve-3d"]').count())
await page.screenshot({ path: '.debugger/prod-reader.png' })
await browser.close()
